name: Coracle.Raft - Project Build and Integration Testing
on:
  push:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    if: ${{ always() }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x  
    - name: Build Solution
      run: dotnet build --configuration Release
    - name: Test - Candidacy, Elections, Leader Establishment, Command Handling, Configuration Changes etc
      run: dotnet test --logger trx --results-directory "CandidacyAndLeaderWorkflowTestResults-${{ matrix.os }}" --filter FullyQualifiedName~CandidacyAndLeaderWorkflowTest
      if: ${{ always() }}
    - name: Test - Follower replication, snapshot installation etc
      run: dotnet test --logger trx --results-directory "FollowerWorkflowTestResults-${{ matrix.os }}" --filter FullyQualifiedName~FollowerWorkflowTest
      if: ${{ always() }}
    - name: Test - Configuration Changes involving leader decommission, etc 
      run: dotnet test --logger trx --results-directory "LeaderEjectionWorkflowTestResults-${{ matrix.os }}" --filter FullyQualifiedName~LeaderEjectionWorkflowTest
      if: ${{ always() }}
    - name: Test - Log Chain Operations, Data manipulations, etc
      run: dotnet test --logger trx --results-directory "LogHolderWorkflowTestResults-${{ matrix.os }}" --filter FullyQualifiedName~LogHolderWorkflowTest
      if: ${{ always() }}
    - name: Test - Compaction eligibility, Merging of LogEntries and Snapshot creation, etc
      run: dotnet test --logger trx --results-directory "SnapshotWorkflowTestResults-${{ matrix.os }}" --filter FullyQualifiedName~SnapshotWorkflowTest
      if: ${{ always() }}
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ matrix.os }}
        path: | 
          CandidacyAndLeaderWorkflowTestResults-${{ matrix.os }} 
          FollowerWorkflowTestResults-${{ matrix.os }} 
          LeaderEjectionWorkflowTestResults-${{ matrix.os }} 
          LogHolderWorkflowTestResults-${{ matrix.os }} 
          SnapshotWorkflowTestResults-${{ matrix.os }} 
        retention-days: 5
      if: ${{ always() }}
    - name: Download All Workflow Run Artifacts
      uses: actions/download-artifact@v3
      if: ${{ always() }}
